apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: "metrics-server-{{cluster}}"
      annotations:
        argocd.argoproj.io/sync-wave: "-90"
      labels:
        app: metrics-server
      finalizers:
        - resources-finalizers.argocd.argoproj.io
    spec:
      project: cluster-management-root
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.13.0
        chart: metrics-server
        helm:
          releaseName: metrics-server
          valuesObject:
            podLabels:
              app: metrics-server
              team: sre
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
      destination:
        server: https://kubernetes.default.svc
        namespace: metrics-server
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
