apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: "kyverno-policies-{{cluster}}"
      annotations:
        argocd.argoproj.io/sync-wave: "-90"
      finalizers:
        - resources-finalizers.argocd.argoproj.io
      labels:
        app: kyverno-policies
        team: platform
        tier: infrastructure
    spec:
      project: cluster-management-root
      destination:
        namespace: kyverno-policies
        server: "{{server}}"
      sources:
        - repoURL: https://kyverno.github.io/kyverno/
          chart: kyverno
          targetRevision: 2.6.0
          helm:
            releaseName: kyverno
        - helm:
            releaseName: kyverno-policies
          path: .
          repoURL: https://github.com/ssah-blr/helm-kyverno-policies
          targetRevision: v1.2.0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
