apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-management-root
  namespace: argocd
spec:
  description: Project for managing cluster-level add-ons
  sourceRepos:
    - 'https://github.com/ssah-blr/argocd.git' # Add your GitHub repo
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: Event
  syncWindows: []
